#############################################################################
# Makefile for building: PowerDesigner
# Generated by qmake (2.01a) (Qt 4.6.0) on: ??? ?? 13 20:55:52 2010
# Project:  PowerDesigner.pro
# Template: lib
# Command: c:\qt\2009.05\qt\bin\qmake.exe -spec ../Qt/2009.05/qt/mkspecs/win32-g++ -win32 -o Makefile PowerDesigner.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/qt/2009.05/qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: PowerDesigner.pro  ../Qt/2009.05/qt/mkspecs/win32-g++/qmake.conf ../Qt/2009.05/qt/mkspecs/qconfig.pri \
		../Qt/2009.05/qt/mkspecs/features/qt_functions.prf \
		../Qt/2009.05/qt/mkspecs/features/qt_config.prf \
		../Qt/2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../Qt/2009.05/qt/mkspecs/features/default_pre.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/default_pre.prf \
		../projects/qt-creator-1.3.0/qtcreator.pri \
		../projects/qt-creator-1.3.0/src/qtcreatorplugin.pri \
		../projects/qt-creator-1.3.0/src/libs/aggregation/aggregation.pri \
		../projects/qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../projects/qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem.pri \
		../projects/qt-creator-1.3.0/src/libs/utils/utils.pri \
		../projects/qt-creator-1.3.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../projects/qt-creator-1.3.0/src/plugins/coreplugin/coreplugin.pri \
		../Qt/2009.05/qt/mkspecs/features/debug.prf \
		../Qt/2009.05/qt/mkspecs/features/debug_and_release.prf \
		../Qt/2009.05/qt/mkspecs/features/default_post.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/default_post.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/rtti.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/exceptions.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/stl.prf \
		../Qt/2009.05/qt/mkspecs/features/shared.prf \
		../Qt/2009.05/qt/mkspecs/features/dll.prf \
		../Qt/2009.05/qt/mkspecs/features/warn_on.prf \
		../Qt/2009.05/qt/mkspecs/features/qt.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/thread.prf \
		../Qt/2009.05/qt/mkspecs/features/moc.prf \
		../Qt/2009.05/qt/mkspecs/features/win32/windows.prf \
		../Qt/2009.05/qt/mkspecs/features/resources.prf \
		../Qt/2009.05/qt/mkspecs/features/uic.prf \
		../Qt/2009.05/qt/mkspecs/features/yacc.prf \
		../Qt/2009.05/qt/mkspecs/features/lex.prf \
		../Qt/2009.05/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../Qt/2009.05/qt/mkspecs/win32-g++ -win32 -o Makefile PowerDesigner.pro
../Qt/2009.05/qt/mkspecs/qconfig.pri:
../Qt/2009.05/qt/mkspecs/features/qt_functions.prf:
../Qt/2009.05/qt/mkspecs/features/qt_config.prf:
../Qt/2009.05/qt/mkspecs/features/exclusive_builds.prf:
../Qt/2009.05/qt/mkspecs/features/default_pre.prf:
../Qt/2009.05/qt/mkspecs/features/win32/default_pre.prf:
../projects/qt-creator-1.3.0/qtcreator.pri:
../projects/qt-creator-1.3.0/src/qtcreatorplugin.pri:
../projects/qt-creator-1.3.0/src/libs/aggregation/aggregation.pri:
../projects/qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../projects/qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem.pri:
../projects/qt-creator-1.3.0/src/libs/utils/utils.pri:
../projects/qt-creator-1.3.0/src/plugins/coreplugin/coreplugin_dependencies.pri:
../projects/qt-creator-1.3.0/src/plugins/coreplugin/coreplugin.pri:
../Qt/2009.05/qt/mkspecs/features/debug.prf:
../Qt/2009.05/qt/mkspecs/features/debug_and_release.prf:
../Qt/2009.05/qt/mkspecs/features/default_post.prf:
../Qt/2009.05/qt/mkspecs/features/win32/default_post.prf:
../Qt/2009.05/qt/mkspecs/features/win32/rtti.prf:
../Qt/2009.05/qt/mkspecs/features/win32/exceptions.prf:
../Qt/2009.05/qt/mkspecs/features/win32/stl.prf:
../Qt/2009.05/qt/mkspecs/features/shared.prf:
../Qt/2009.05/qt/mkspecs/features/dll.prf:
../Qt/2009.05/qt/mkspecs/features/warn_on.prf:
../Qt/2009.05/qt/mkspecs/features/qt.prf:
../Qt/2009.05/qt/mkspecs/features/win32/thread.prf:
../Qt/2009.05/qt/mkspecs/features/moc.prf:
../Qt/2009.05/qt/mkspecs/features/win32/windows.prf:
../Qt/2009.05/qt/mkspecs/features/resources.prf:
../Qt/2009.05/qt/mkspecs/features/uic.prf:
../Qt/2009.05/qt/mkspecs/features/yacc.prf:
../Qt/2009.05/qt/mkspecs/features/lex.prf:
../Qt/2009.05/qt/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../Qt/2009.05/qt/mkspecs/win32-g++ -win32 -o Makefile PowerDesigner.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) c:/creatorframework/lib/qtcreator/plugins/winnux/libPowerDesigner.a
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
