#############################################################################
# Makefile for building: libPowerDesigner.so
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? 1? 11 10:55:23 2010
# Project:  PowerDesigner.pro
# Template: lib
# Command: /opt/qtsdk-2009.05/qt/bin/qmake -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PowerDesigner.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DIDE_LIBRARY_BASENAME=\"lib\" -DWITH_TESTS -DQT_NO_CAST_TO_ASCII -DPOWERDESIGNER_LIBRARY -DQT_PLUGIN -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -fvisibility=hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.05/qt/include/QtCore -I/opt/qtsdk-2009.05/qt/include/QtTest -I/opt/qtsdk-2009.05/qt/include -I../qt-creator-1.3.0/src/libs -I/home/lihaibo/dev/qt-creator-1.3.0/tools -I../qt-creator-1.3.0/src/plugins -I.moc/debug-shared
LINK          = g++
LFLAGS        = -Wl,-z,origin '-Wl,-rpath,/opt/qtsdk-2009.05/qt/lib:$$ORIGIN:$$ORIGIN/..:$$ORIGIN/../..' -shared -Wl,-soname,libPowerDesigner.so
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.05/qt/lib -L/home/lihaibo/dev/myQtCreator//lib/qtcreator/plugins/Nokia -L/home/lihaibo/dev/myQtCreator//lib/qtcreator -L/home/lihaibo/dev/myQtCreator//lib/qtcreator/plugins/winnux -lAggregation -lExtensionSystem -lUtils -lCore -lQtTest -L/opt/qtsdk-2009.05/qt/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/debug-shared/

####### Files

SOURCES       = powerdesignerplugin.cpp .moc/debug-shared/moc_powerdesignerplugin.cpp
OBJECTS       = .obj/debug-shared/powerdesignerplugin.o \
		.obj/debug-shared/moc_powerdesignerplugin.o
DIST          = /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../qt-creator-1.3.0/qtcreator.pri \
		../qt-creator-1.3.0/src/qtcreatorplugin.pri \
		../qt-creator-1.3.0/src/libs/aggregation/aggregation.pri \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem.pri \
		../qt-creator-1.3.0/src/libs/utils/utils.pri \
		../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/hide_symbols.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		PowerDesigner.pro
QMAKE_TARGET  = PowerDesigner
DESTDIR       = ../myQtCreator/lib/qtcreator/plugins/winnux/
TARGET        = libPowerDesigner.so
TARGETD       = libPowerDesigner.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../myQtCreator/lib/qtcreator/plugins/winnux/$(TARGET)

../myQtCreator/lib/qtcreator/plugins/winnux/$(TARGET): ../myQtCreator/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../myQtCreator/lib/qtcreator/plugins/winnux/ || $(MKDIR) ../myQtCreator/lib/qtcreator/plugins/winnux/ 
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../myQtCreator/lib/qtcreator/plugins/winnux/



Makefile: PowerDesigner.pro  /opt/qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../qt-creator-1.3.0/qtcreator.pri \
		../qt-creator-1.3.0/src/qtcreatorplugin.pri \
		../qt-creator-1.3.0/src/libs/aggregation/aggregation.pri \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem.pri \
		../qt-creator-1.3.0/src/libs/utils/utils.pri \
		../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin_dependencies.pri \
		../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin.pri \
		/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/hide_symbols.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.05/qt/lib/libQtTest.prl \
		/opt/qtsdk-2009.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PowerDesigner.pro
/opt/qtsdk-2009.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
../qt-creator-1.3.0/qtcreator.pri:
../qt-creator-1.3.0/src/qtcreatorplugin.pri:
../qt-creator-1.3.0/src/libs/aggregation/aggregation.pri:
../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_dependencies.pri:
../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem.pri:
../qt-creator-1.3.0/src/libs/utils/utils.pri:
../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin_dependencies.pri:
../qt-creator-1.3.0/src/plugins/coreplugin/coreplugin.pri:
/opt/qtsdk-2009.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/unix/hide_symbols.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.05/qt/lib/libQtTest.prl:
/opt/qtsdk-2009.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PowerDesigner.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/debug-shared/PowerDesigner1.0.0 || $(MKDIR) .obj/debug-shared/PowerDesigner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/debug-shared/PowerDesigner1.0.0/ && $(COPY_FILE) --parents PowerDesigner.pluginspec .obj/debug-shared/PowerDesigner1.0.0/ && $(COPY_FILE) --parents powerdesignerplugin.h PowerDesigner_global.h .obj/debug-shared/PowerDesigner1.0.0/ && $(COPY_FILE) --parents powerdesignerplugin.cpp .obj/debug-shared/PowerDesigner1.0.0/ && (cd `dirname .obj/debug-shared/PowerDesigner1.0.0` && $(TAR) PowerDesigner1.0.0.tar PowerDesigner1.0.0 && $(COMPRESS) PowerDesigner1.0.0.tar) && $(MOVE) `dirname .obj/debug-shared/PowerDesigner1.0.0`/PowerDesigner1.0.0.tar.gz . && $(DEL_FILE) -r .obj/debug-shared/PowerDesigner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_copy2build_make_all: ../myQtCreator/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec
compiler_copy2build_clean:
	-$(DEL_FILE) ../myQtCreator/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec
../myQtCreator/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec: PowerDesigner.pluginspec
	cp -f PowerDesigner.pluginspec ../myQtCreator/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec

compiler_moc_header_make_all: .moc/debug-shared/moc_powerdesignerplugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/debug-shared/moc_powerdesignerplugin.cpp
.moc/debug-shared/moc_powerdesignerplugin.cpp: PowerDesigner_global.h \
		../qt-creator-1.3.0/src/libs/extensionsystem/iplugin.h \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_global.h \
		powerdesignerplugin.h
	/opt/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) powerdesignerplugin.h -o .moc/debug-shared/moc_powerdesignerplugin.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_copy2build_clean compiler_moc_header_clean 

####### Compile

.obj/debug-shared/powerdesignerplugin.o: powerdesignerplugin.cpp powerdesignerplugin.h \
		PowerDesigner_global.h \
		../qt-creator-1.3.0/src/libs/extensionsystem/iplugin.h \
		../qt-creator-1.3.0/src/libs/extensionsystem/extensionsystem_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/powerdesignerplugin.o powerdesignerplugin.cpp

.obj/debug-shared/moc_powerdesignerplugin.o: .moc/debug-shared/moc_powerdesignerplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/debug-shared/moc_powerdesignerplugin.o .moc/debug-shared/moc_powerdesignerplugin.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ || $(MKDIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ 
	-$(INSTALL_PROGRAM) "../myQtCreator/lib/qtcreator/plugins/winnux/$(TARGET)" "$(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ 


install_pluginspec: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ || $(MKDIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ 
	-$(INSTALL_FILE) /home/lihaibo/dev/PowerDesigner/PowerDesigner.pluginspec $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/


uninstall_pluginspec:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/PowerDesigner.pluginspec
	-$(DEL_DIR) $(INSTALL_ROOT)/lib/qtcreator/plugins/winnux/ 


install:  install_target install_pluginspec  FORCE

uninstall: uninstall_target uninstall_pluginspec   FORCE

FORCE:

