#ifndef POWERDESIGNER_GLOBAL_H
#define POWERDESIGNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POWERDESIGNER_LIBRARY)
#  define POWERDESIGNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POWERDESIGNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POWERDESIGNER_GLOBAL_H
